// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMOiQhxEan9kKJeS9fOd-BRrwf-etr3Y0',
    appId: '1:826629246245:web:a99bdb490632c005359ecc',
    messagingSenderId: '826629246245',
    projectId: 'flutter-e-commerce-practise',
    authDomain: 'flutter-e-commerce-practise.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-practise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkdH2168nHWYC4bBq1JoqXfLVxyexPM_Y',
    appId: '1:826629246245:android:abf0de1be2210231359ecc',
    messagingSenderId: '826629246245',
    projectId: 'flutter-e-commerce-practise',
    storageBucket: 'flutter-e-commerce-practise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT8E-YqikSaJmwQsUqb1bcQ1JMeC0IY4M',
    appId: '1:826629246245:ios:c984d64c51d31c14359ecc',
    messagingSenderId: '826629246245',
    projectId: 'flutter-e-commerce-practise',
    storageBucket: 'flutter-e-commerce-practise.appspot.com',
    androidClientId: '826629246245-a7os29n7iu22amb2umlnj6m13ht1bb94.apps.googleusercontent.com',
    iosClientId: '826629246245-1b732hgfj9udj4cqn8o32ctkrdjhe8f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMOiQhxEan9kKJeS9fOd-BRrwf-etr3Y0',
    appId: '1:826629246245:web:4e4e10b306834636359ecc',
    messagingSenderId: '826629246245',
    projectId: 'flutter-e-commerce-practise',
    authDomain: 'flutter-e-commerce-practise.firebaseapp.com',
    storageBucket: 'flutter-e-commerce-practise.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT8E-YqikSaJmwQsUqb1bcQ1JMeC0IY4M',
    appId: '1:826629246245:ios:c984d64c51d31c14359ecc',
    messagingSenderId: '826629246245',
    projectId: 'flutter-e-commerce-practise',
    storageBucket: 'flutter-e-commerce-practise.appspot.com',
    androidClientId: '826629246245-a7os29n7iu22amb2umlnj6m13ht1bb94.apps.googleusercontent.com',
    iosClientId: '826629246245-1b732hgfj9udj4cqn8o32ctkrdjhe8f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

}